In [3]:
from nba_api.stats.static import players,teams
import pandas as pd
import requests
import sys
import os
import time
from datetime import datetime

def format_date_to_url(date):
    # Convert date from YYYYMMDD to datetime object
    date_obj = datetime.strptime(str(date), '%Y%m%d')
    
    # Format the date as MM%2FDD%2FYYYY
    formatted_date = date_obj.strftime('%m%%2F%d%%2F%Y')
    
    return formatted_date

# Example usage
def get_dates(start_year,end_year):
    dates=[]
    for year in range(start_year,end_year):
    
        for team in teams.get_teams():
            team_id=team['id']
            path = '../../shot_data/team/'+str(year)+'ps/'+str(team_id)+'.csv'
            if os.path.exists(path):
                df=pd.read_csv(path)
    
                df=df[['PLAYER_ID','TEAM_ID','HTM','VTM','GAME_DATE','GAME_ID']]
                df.drop_duplicates(inplace=True)
                df['year']=year
                dates.append(df)
    return pd.concat(dates)

start_year=2014
end_year=2024
dateframe=get_dates(start_year,end_year)

dates=dateframe['GAME_DATE'].unique().tolist()


psdata=[]

for year in range(start_year,end_year):
    df=pd.read_csv('../../shot_data/series/'+str(year)+'.csv')
    psdata.append(df)

psdata=pd.concat(psdata)
psdata

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,CATCH_SHOOT_FG_PCT,POST_TOUCH_FG_PCT,ELBOW_TOUCH_FG_PCT,POST_TOUCH_PTS,PAINT_TOUCH_FG_PCT,ELBOW_TOUCH_PTS,PAINT_TOUCH_PTS,CATCH_SHOOT_PTS,year,date
0,101187,Alan Anderson,Alan,1610612751,BKN,31.0,1,1,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014,20140419
1,101161,Amir Johnson,Amir,1610612761,TOR,27.0,1,0,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014,20140419
2,101154,Andray Blatche,Andray,1610612751,BKN,27.0,1,1,0,1.0,...,0.0,0.0,0.0,0.0,0.4,1.0,5.0,0.0,2014,20140419
3,2738,Andre Iguodala,Andre,1610612744,GSW,30.0,1,1,0,1.0,...,0.0,0.0,1.0,2.0,1.0,2.0,2.0,0.0,2014,20140419
4,2757,Beno Udrih,Beno,1610612763,MEM,31.0,1,0,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2014,20140419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,1629060,Rui Hachimura,Rui,1610612747,LAL,25.0,1,1,0,1.0,...,0.4,0.0,0.5,0.0,0.0,2.0,0.0,5.0,2023,20230424
1724,1630583,Santi Aldama,Santi,1610612763,MEM,22.0,1,0,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,20230424
1725,1628972,Troy Brown Jr.,Troy,1610612747,LAL,23.0,1,1,0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,2023,20230424
1726,1626145,Tyus Jones,Tyus,1610612763,MEM,27.0,1,0,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2023,20230424
1727,1630214,Xavier Tillman,Xavier,1610612763,MEM,24.0,1,0,1,0.0,...,0.0,0.0,0.5,0.0,0.4,2.0,6.0,0.0,2023,20230424

In [5]:
frames= []
count=0
index_master=pd.read_csv('index_master_ps.csv')
index_master=index_master[index_master.team!='TOT']
index_master['team_id']=index_master['team_id'].astype(int)
index_master['nba_id']=index_master['nba_id'].astype(int)

for year in range(2014, 2026):
    # Load the game data for the specific year.
    df = psdata[psdata.year==year].reset_index(drop=True)

    team_map=dict(zip(df['TEAM_ID'],df['TEAM_ABBREVIATION']))
    
    # Filter index_master for the current year.
    year_index = index_master[index_master['year'] == year].reset_index()

    # Process each unique date in the dataset.
    for date in df['date'].unique().tolist():
        datedf=df[df.date==date].reset_index(drop=True)
        datedf=datedf.drop_duplicates(subset=['PLAYER_ID','date'])
        # Filter game data by date.
        
        gameframe = dateframe[dateframe['GAME_DATE'] == date].reset_index()
        gameframe.rename(columns={'GAME_DATE':'date'},inplace=True)
        # Get the unique team and game data for the specific date from gameframe.
        to_merge = gameframe[['TEAM_ID', 'GAME_ID', 'date', 'year']].drop_duplicates().reset_index(drop=True)
        

        save_frame=datedf.merge(to_merge,on=['TEAM_ID','date','year'],how='left')

      
        save_frame.drop_duplicates(inplace=True)

        
        # Merge game data with index_master to ensure correct team alignment.
        # Match on 'player' and 'team' columns from index_master and 'TEAM_ID' from the game data.

        # Identify rows where the merge may have issues.
        if save_frame['GAME_ID'].isna().any():
        
            missing=save_frame[save_frame['GAME_ID'].isna()].reset_index(drop=True)
            save_frame.dropna(subset='GAME_ID',inplace=True)
            missing.drop(columns=['GAME_ID','TEAM_ID','TEAM_ABBREVIATION'],inplace=True)

            missing=missing.merge(gameframe,on=['PLAYER_ID','year','date'],how='left')
            missing['TEAM_ABBREVIATION']=missing['TEAM_ID'].map(team_map)
    
            save_frame=pd.concat([save_frame,missing])

        if save_frame['GAME_ID'].isna().any():
        
            missing=save_frame[save_frame['GAME_ID'].isna()].reset_index(drop=True)
            missing.drop(columns='GAME_ID',inplace=True)
            save_frame.dropna(subset='GAME_ID',inplace=True)
            missed=[]
            
            for missed_player in missing['PLAYER_ID'].unique().tolist():
                missing_frame=missing[missing.PLAYER_ID==missed_player].reset_index(drop=True)
                temp_index=year_index[year_index.nba_id==missed_player].reset_index(drop=True)
                team_id=temp_index.iloc[0]['team_id']
                team=temp_index.iloc[0]['team']
                missing_frame['TEAM_ID']=int(team_id)
                missing_frame['TEAM_ABBREVIATION']=team
                missing_frame= missing_frame.merge(to_merge,on=['TEAM_ID','date','year'],how='left')
                missed.append(missing_frame)

            missing=pd.concat(missed)
            save_frame=pd.concat([save_frame,missing])
        if save_frame['GAME_ID'].isna().any():
        
            missing=save_frame[save_frame['GAME_ID'].isna()].reset_index(drop=True)
            missing.drop(columns='GAME_ID',inplace=True)
            save_frame.dropna(subset='GAME_ID',inplace=True)
            missed=[]
            
            for missed_player in missing['PLAYER_ID'].unique().tolist():
                missing_frame=missing[missing.PLAYER_ID==missed_player].reset_index(drop=True)
                temp_index=year_index[year_index.nba_id==missed_player].reset_index(drop=True)
                team_id=temp_index.iloc[1]['team_id']
                team=temp_index.iloc[1]['team']
                missing_frame['TEAM_ID']=int(team_id)
                missing_frame['TEAM_ABBREVIATION']=team
                missing_frame= missing_frame.merge(to_merge,on=['TEAM_ID','date','year'],how='left')
                missed.append(missing_frame)

            missing=pd.concat(missed)
            save_frame=pd.concat([save_frame,missing])

        if save_frame['GAME_ID'].isna().any():
        
            missing=save_frame[save_frame['GAME_ID'].isna()].reset_index(drop=True)
            missing.drop(columns='GAME_ID',inplace=True)
            save_frame.dropna(subset='GAME_ID',inplace=True)
            missed=[]
            
            for missed_player in missing['PLAYER_ID'].unique().tolist():
                missing_frame=missing[missing.PLAYER_ID==missed_player].reset_index(drop=True)
                temp_index=year_index[year_index.nba_id==missed_player].reset_index(drop=True)
                team_id=temp_index.iloc[2]['team_id']
                team=temp_index.iloc[2]['team']
                missing_frame['TEAM_ID']=int(team_id)
                missing_frame['TEAM_ABBREVIATION']=team
                missing_frame= missing_frame.merge(to_merge,on=['TEAM_ID','date','year'],how='left')
                missed.append(missing_frame)

            missing=pd.concat(missed)
            save_frame=pd.concat([save_frame,missing])
            
        if save_frame['GAME_ID'].isna().any():
            missing=save_frame[save_frame['GAME_ID'].isna()]
            print('test point')
            print(missing)
        
        # Remove any duplicate entries after the merge.
        save_frame.drop_duplicates(inplace=True)
        save_frame['GAME_ID']=save_frame['GAME_ID'].astype(int)
        # Save each game by unique GAME_ID.
        for game_id in save_frame['GAME_ID'].unique():
            gameid_frame = save_frame[save_frame['GAME_ID'] == game_id].reset_index(drop=True)
            gameid_frame.to_csv(f'{year}/{game_id}.csv', index=False)
            count += 1
            
            # Exit early for testing if more than 8 files are saved.